### ISSUE TITLE
User can configure per project, if he wants to be notified

### ISSUE THREAD

**Issue by cforce** [drewkeller/redmine_digest#1]
Sending  emails to everyone without one subcribed this information, wonÄt be a accepted by our users.
In Project overview or in "My account" there should be an option for a user to subscribe or unsubscribe for activity digest mails based on the the available digest jobs running (e.g. daily, weekly..)
This should be configurable  per project by user. Furthermore the read access rights for informations, printed out in that digest must be taken into account. E.g. If one has no read access to project archiv he shouldn't get information on new revisions.

An more advanced option would be:

User is able to set  per digest per project about what doument types ( Tickets, Changesets, News, Wiki,.. ) and change type (new, edit or removed) he want to be notified in the digest.

However ur plugin is a first good start. Tx for contributing

**Comment by drewkeller** [comment]
Do you know an example of a plugin that has subscribe/unsubscribe per 
user in it?

I have not written any Ruby code or used Redmine until last week so it's 
easier to follow an example.

I imagine that in order to respect more restricted viewing permissions, 
a separate email would need to be sent for each type of user role. I 
don't see a place to set permissions for a specific user. Does that 
sound right?

Thanks
-drew

**Comment by cforce** [comment]
Subscribing just means a user canclick checkboxes for being notfied of certain information on certain schedule. The model must reference userid and save digest schedule (daily, weekly), which ressources ( see activity site right panel, there is code behind which will give u all event.type (wiki, revision, thread, issue,...), which event.project ( there is a method to get all projects, see projects drop-down in main menu).

When schedule start job for creating mails, you must query per userid activities, filter by period (day, 1 week backwards),  where, filter by event type (same methods used in activity tab) and action type, then retrieve data and create out mail of this.  (see "activity view":http://www.redmine.org/projects/redmine/repository/entry/trunk/app/views/activities/index.html.erb)
You shall hardly reuse many of the "activity controller":http://www.redmine.org/projects/redmine/repository/revisions/6197/entry/trunk/app/controllers/activities_controller.rb functions  then you only get information the user is authorized.

**Comment by cforce** [comment]
This code may help as well:

http://www.redmine.org/plugins/redmine_newissuealerts
http://www.redmine.org/plugins/notifo

**Comment by drewkeller** [comment]
This is implemented in v0.1.0

**Comment by cforce** [comment]
Tx a lot for this extension.
However the user can't subscribe or unsubscribe for activity digest mails based on the the available digest jobs running (e.g. daily, weekly..) and can't configure this per project.

At the moment it is all or nothing.

I oir scenario some people wanna get daily other weekly digest depending on which project they work. Some are very active some not. That the case hey must get notified in shorther period than in other projekts.
I can't configure that staticly in the scheduled job, because users wanna choose themself how they wanna be notified.

Being able to set which ressouces shall be included per digest, we could offer several daily and weeekly digest with different content and allow user to select per project what and when and for which project he wanna get informations.

Tx so far for ur work and this nice plugin.
