### ISSUE TITLE
W�hrend des Versands ist ein Fehler aufgetreten (Missing template digest_mailer/digest.text.plain.rhtml in view path app/views)

### ISSUE THREAD

**Issue by derbaron** [drewkeller/redmine_digest#10]
Doesnt work though...

On latest Bitnami Redmine Stack windows

**Comment by kevinpostal** [comment]
I have same issue

**Comment by drewkeller** [comment]
Something seems to have been changed in redmine 1.3 to cause this error. See issue #20 and https://github.com/drewkeller/redmine_digest/commit/df59d680db2bc51c00bfd5a461911102c4060a40 which fixes it for me.
