### ISSUE TITLE
Postresql requires booleans to be in quotes

### ISSUE THREAD

**Issue by sbelak** [drewkeller/redmine_digest#16]
Using Redmine with Postresql 9.0.4 I get the following error upon trying to send a digest:

``` sql
An error occurred while sending the digest (PGError: ERROR: operator does not exist: boolean = integer LINE 1: SELECT *
 FROM "users" WHERE (admin=1) AND ( ("users"."type" ... ^ HINT: No operator matches the given name and argument type(s).
 You might need to add explicit type casts. : SELECT * FROM "users" WHERE (admin=1) AND ( ("users"."type" = 'User' OR 
"users"."type" = 'AnonymousUser' ) ) )
```

The problem seems to be in app/models/digest_mailer.rb:59

**Comment by drewkeller** [comment]
I have never used Postgresql. You can try this modification and see if it works. Doesn't seem to hurt anything for MySQL.
`user = User.find(:all, :conditions => ["admin='1'"]).first`
