### ISSUE TITLE
Couldn't find User with ID=32

### ISSUE THREAD

**Issue by jmartsch** [drewkeller/redmine_digest#2]
Everytime I try to send a mail i get the upper error. User 32 is a group that i created in my redmine installation. Any ideas how to solve the problem?

**Comment by cforce** [comment]
Maybe the Member.find() method also retrieves groups, not only users?

 members = Member.find(:all, :conditions => ["project_id = " + project[:id].to_s]).each { |m|
            user = User.find(m.user_id)
            recipients << user.mail unless not user.active?

**Comment by jmartsch** [comment]
It seems so, because groups are stored in the user table. The difference to normal users is that they have no login name (column login in table users is empty). Could you rewrite the query for that? I don´t know ruby and stuff.

**Comment by cforce** [comment]
I don´t know ruby and stuff, too.

But you can try..

members = Member.find(:all, conditions => ["user_id=? and project_id = " + project[:id].to_s]).each { |m|
user = User.find(m.user_id)

**Comment by drewkeller** [comment]
Turns out, user is accessible from member (member.user) so I was actually able to simplify my code.

**Comment by jmartsch** [comment]
thanks for the fix. I will try it soon
