### ISSUE TITLE
Please provide example

### ISSUE THREAD

**Issue by sgourichon** [drewkeller/redmine_digest#22]
People love example. Html file, even screenshot, to get a hint about how it feels when installed.

**Comment by drewkeller** [comment]
There are three examples in the readme. But no screenshot.

**Comment by sgourichon** [comment]
Thanks. Sorry I was probably unclear. I had read the Readme before writing, of course. There in each of your examples you reuse the word "digest" from the plugin description, but there is no definition of what you mean nor example output (even a text-based copy-paste).

For example, does it just look like http://www.redmine.org/activity ? Is it somewhat different (reimplemented, different focus), etc.

## The bigger picture

For a visitor browsing through many plugin descriptions and possible solutions to his need, a sample output from your plugin is worth a thousand answers you don't even have to make explicit.

Of course in principle the visitors can test drive all plugins etc, but in practice they focus on those that quickly provide the best hints about what they actually do.

Is my request clearer now ?
