### ISSUE TITLE
undefined method `ssl?' for nil:NilClass

### ISSUE THREAD

**Issue by jmartsch** [drewkeller/redmine_digest#3]
I get the following error when trying to send a digest:
An error occurred while sending the digest (undefined method `ssl?' for nil:NilClass).

I am calling my redmine via http not https.

**Comment by drewkeller** [comment]
Can you include the full trace?

Which method are you using to send the digest when this happens? If 
you're doing it from the plugin configuration page, I would be curious 
whether you see that error when you send the test email from the email 
notifications settings tab (I use almost identical code).

**Comment by GlenRayward** [comment]
I also get this error when using the settings tab and Send digests for all digest-enabled projects:
An error occurred while sending the digest (undefined method `ssl?' for nil:NilClass)

From Log:
Processing DigestController#send_all (for 10.6.5.90 at 2011-08-24 10:27:40) [GET]

#   Parameters: {"action"=>"send_all", "controller"=>"digest"}

Start: 7
Days : 7
*\* Processing project 'Project one'...
undefined method `ssl?' for nil:NilClass
Redirected to http://xxxxxxxIPxxxxxx/redmine/settings/plugin/digest
Completed in 234ms (DB: 16) | 302 Found [http://xxxxxxxIPxxxxxx/redmine/digest/send_all]

Processing SettingsController#plugin (for 10.6.5.90 at 2011-08-24 10:27:40) [GET]
  Parameters: {"action"=>"plugin", "id"=>"digest", "controller"=>"settings"}
Rendering template within layouts/admin
Rendering settings/plugin
Completed in 47ms (View: 47, DB: 0) | 200 OK [http://xxxxxxxIPxxxxxx/redmine/settings/plugin/digest]

**Comment by drewkeller** [comment]
ok, that's a little more detail. It looks like you're using http, not https, judging from the redirects.

I'll try out the Bitnami setup and see if I can duplicate this issue on it. I'm going to assume you're using a vanilla setup (plus digest) on Redmine 1.2.0 or 1.2.1. In the meantime, here's the batch script I use to start my server to output trace with line numbers.

<pre>
@echo off
set environment=development
::set environment=production
set folder=c:\v\wamp
set redmine=redmine-1.2.1

cd "%folder%\ruby\bin"
ruby.exe mongrel_rails mongrel::start ^
    -a 127.0.0.1 -p 3001 -e %environment% -c "%folder%/apps/%redmine%" ^
    --prefix /redmine

pause
</pre>

**Comment by GlenRayward** [comment]
Sorry I don’t know what to do with that script, I'm using Win7 too.
Unfortunately I have Many plugins installed, maybe there is a conflict.

-----Original Message-----

**Comment by drewkeller** [comment]
Here's the batch script I used for the standard Bitnami setup. Create a file called "Start Redmine.bat" or some such on your desktop and put this code in it. You'll have to stop the mongrel services (in the Bitnami manager or Windows Services control panel) before running the script or they will conflict with each other. Comment out whichever environment you're NOT using by preceding it double colon (::)... the script below is for development environment and has production commented out.

I'm running on Windows 7, as well. I didn't get the ssl error when I tested with rake task and the configure plugins page (both ways worked for me).

<pre>
@echo off
set environment=development
::set environment=production
set folder=c:\Program Files\BitNami Redmine Stack
set redmine=redmine
set rakefile=%folder%/apps/%redmine%/Rakefile

CALL C:\PROGRA~1\BITNAM~1\scripts\setenv.bat

cd "%folder%\ruby\bin"
::ruby rake -f "%rakefile%" db:migrate_plugins RAILS_ENV=%environment% --trace

rake redmine:send_digest start=7 days=8 RAILS_ENV="production" -f "%rakefile%"

pause
</pre>

**Comment by jmartsch** [comment]
It happened to me also from the settings tab and "Send digests for all digest-enabled projects". I also get the error when calling it via rake on a console.
My system is a Debian 5.0 lenny with Apache 2 and mod_rails (aka Phusion Passenger). I am using some redmine plugins: local avatars, redmine_ics_export, redmine_lightbox, redmine_closebutton and redmine_stealth.

Here is the trace from the rake call
```*\* Invoke redmine:send_digest (first_time)
*\* Execute redmine:send_digest

# 

Start: 7
Days : 8
*\* Processing project 'Web'...
Summarizing: 2011-08-17 to 2011-08-25 (8 days)
From 17.08.2011 to 24.08.2011
Found 37 events.
rake aborted!
undefined method `ssl?' for nil:NilClass
On line #52 of vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml

```
49: <% if formatted_day == formatted_date -%>
50:   <h3><%= formatted_date %></h3>
51: <% else %> 
52:   <h3><%= formatted_day %> <span style="font-weight:normal;">(<%= formatted_date %>)</span></h3>
53: <% end -%>
54: <dl>
55: <% @events_by_day[day].sort {|x,y| x.event_datetime <=> y.event_datetime }.each do |e| -%>

app/helpers/application_helper.rb:879:in `avatar_without_local'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:52:in `_run_rhtml_vendor47plugins47redmine_digest47app47views47digest_mailer47digest46text46html46rhtml'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:49:in `each'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:49:in `_run_rhtml_vendor47plugins47redmine_digest47app47views47digest_mailer47digest46text46html46rhtml'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in `each'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in `_run_rhtml_vendor47plugins47redmine_digest47app47views47digest_mailer47digest46text46html46rhtml'
app/models/mailer.rb:417:in `render_multipart'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:29:in `digest'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:152:in `digests'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:127:in `each'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:127:in `digests'
rake (0.8.7) lib/rake.rb:636:in `call'
rake (0.8.7) lib/rake.rb:636:in `execute'
rake (0.8.7) lib/rake.rb:631:in `each'
rake (0.8.7) lib/rake.rb:631:in `execute'
rake (0.8.7) lib/rake.rb:597:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
rake (0.8.7) lib/rake.rb:590:in `invoke_with_call_chain'
rake (0.8.7) lib/rake.rb:583:in `invoke'
rake (0.8.7) lib/rake.rb:2051:in `invoke_task'
rake (0.8.7) lib/rake.rb:2029:in `top_level'
rake (0.8.7) lib/rake.rb:2029:in `each'
rake (0.8.7) lib/rake.rb:2029:in `top_level'
rake (0.8.7) lib/rake.rb:2068:in `standard_exception_handling'
rake (0.8.7) lib/rake.rb:2023:in `top_level'
rake (0.8.7) lib/rake.rb:2001:in `run'
rake (0.8.7) lib/rake.rb:2068:in `standard_exception_handling'
rake (0.8.7) lib/rake.rb:1998:in `run'
rake (0.8.7) bin/rake:31
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
```

```
```

**Comment by drewkeller** [comment]
The top line of that trace seems to indicate something in app/helpers/application_helper.rb:879:in `avatar_without_local'

There are two local avatars plugins. The one from https://github.com/Serafim-III/redmine_local_avatars_003 causes redmine to not even start. The one from https://launchpad.net/redminelocalavatars worked, but didn't seem to cause any issues.

Since I can't duplicate the issue yet, the first thing I would suggest is changing the variable in the view that the trace called out by changing each instance of "formatted_day" and "formatted_date" to "@formatted_day" and "@formatted_date" (add a @ in front of each). I would post it here, but the code gets clobbered, even in a pre tag :/ .

You could also confirm which plugin causes the conflict by removing each one and testing.

**Comment by GlenRayward** [comment]
Thanks, that was easy :P
The last Pause isn’t working...
But I managed to get a screen shot before it exited

No emails are being sent...

The SSL error happens in the config/setting tab within redmine

Cheers

-----Original Message-----

**Comment by GlenRayward** [comment]
Didn't thing attaching a screenshot in outlook would work...
Can I add them to this github?

anyway... Yes i have local avatars too,
So I've removed it and still same problem, 
I then removed Stealth Mode as that is the only other plugin we have in common and no improvement...

Is the trace just the extra info in the CMD window? or does ot produce a file as well somewhere?
If only window:
*\* Invoke redmine:send_digest (first_time)
*\* Execute redmine:send_digest
is the only extra by running trace

**Comment by drewkeller** [comment]
oops, sorry. Forgot to add --trace to the end of this line. Also, it will theoretically stay open if you add cmd /k

<pre>
cmd /k rake redmine:send_digest start=7 days=8 RAILS_ENV="production" -f "%rakefile%" --trace
</pre>

...which ought to get you some output in the console similar to what jmar posted. BUT if it's only happening from the plugins/config and not rake, it should be this command instead (I misread one of your earlier posts)....

<pre>
ruby mongrel_rails mongrel::start -e %environment% -c "%folder%/apps/%redmine%" --prefix /redmine
</pre>


The rake command starts an instance of redmine and then exits. The second one starts mongrel (which runs ruby) and stays running until you exit it, so you can use your browser to access redmine while it is running (you still need your apache and mysql services running).

I don't see a way to post a screenshot on github. You can send it to my email address drew & drewkeller.com (substitute with an @ of course).

**Comment by GlenRayward** [comment]
The rake just gives the usual no events found
And
The Ruby line gives no errors:
*\* Starting Mongrel listening at 0.0.0.0:3000
*\* Starting Rails with production environment...
*\* Mounting Rails at /redmine...
*\* Rails loaded.
*\* Loading any Rails specific GemPlugins
*\* Signals ready.  INT => stop (no restart).
*\* Mongrel 1.1.5 available at 0.0.0.0:3000
*\* Use CTRL-C to stop.

Should I have done it with development environment?
Sorry that I'm not experienced with redmine at all.

What's the difference between the environments and which one am I using / should I use?
I installed Bitnami normally and when i install plugins i use: "rake db:migrate:plugins RAILS_ENV=production"

I'm not trying to Develop Redmine plugins so production?

Cheers
-Glen

-----Original Message-----

**Comment by drewkeller** [comment]
With mongrel running in the console, try to send the digest. If you get an error, it should print out some stuff in the console.

Development puts a lot more messages in the log (see redmine/config/environments/production.rb for other differences). I might be able to figure out what's going on with issue #4 using a log output from a development config, although it's a lot of junk to read through. You would have to make sure the database is set up for the development environment (redmine/config/database.yml). Bitnami uses two different databases (bitnami_redmine for production and redmine_development for development). The easiest way is to just set both to bitnami_redmine, which isn't recommended if you have a plugin in development that might go haywire and do something bad in your database.

**Comment by drewkeller** [comment]
I don't really have anything to add except I installed all of the plugins jmar listed in a Bitnami stack and everything was still working as expected. A good part of my development was in PeppermintTwo OS, so I doubt Linux vs Windows has anything to do with it.

Some of those plugins look really handy. The stealth plugin apparently prevents ALL notifications, not just for events initiated by users who turned on stealth mode (someone created a ticket while I had it in stealth mode and no notifications went out).

RMagic is a real pain. I got it working on one setup but still get an odd error on another every time I start redmine. It was much easier to use mini_magick instead and seems to do the same thing.

**Comment by drewkeller** [comment]
Please see if this is fixed now. I tried two different things I though might fix it.

**Comment by GlenRayward** [comment]
Sorry Drew, no improvement, actually now it produces the ssl error for both test and send all.
No output in console, just:
c:\Program Files\BitNami Redmine Stack\ruby\bin>ruby mongrel_rails mongrel::start -e production -c "c:\Program Files\BitNami Redmine Stack/a
pps/redmine" --prefix /redmine
*\* Starting Mongrel listening at 0.0.0.0:3000
*\* Starting Rails with production environment...
*\* Mounting Rails at /redmine...
*\* Rails loaded.
*\* Loading any Rails specific GemPlugins
*\* Signals ready.  INT => stop (no restart).
*\* Mongrel 1.1.5 available at 0.0.0.0:3000
*\* Use CTRL-C to stop.

-----Original Message-----

**Comment by jmartsch** [comment]
Hi Drew. Thanks for the fix. It works fine now, but i have a suggestion about the behavior of the plugin. I will write this in an seperate issue.

**Comment by drewkeller** [comment]
@Glen: I added a branch that displays some more debug messages in the console. Please download it and try it.

@jmar: Glad it's working for you. There was one place I missed when renaming the plugin, so you'll probably want to update anyway.

**Comment by bitmorse** [comment]
Hi there

I also have this exact same error message. I run Ubuntu 10.4 with Rack 1.1 (Release: 1.3), rake 0.8.7, ruby 1.8.7, Rails 2.3.11 and redmine 1.2.1. 

Do you have any other suggestions on solving the problem? I deselected all projects but one to receive digests. I've been playing around with the amount of days as well.

This /usr/bin/rake redmine:send_digest RAILS_ENV="production" --trace  
outputs this: http://pastebin.com/4QtWWJmV

Would be really happy if someone could give me some hints on where to troubleshoot.

**Comment by drewkeller** [comment]
@sam: If you have any futher problems, it would be helpful if you switch to the extra_debug branch and paste the output from it. Please use a separate issue, since whatever was causing this one seems to be reported as fixed.
