### ISSUE TITLE
Need help setting up cron

### ISSUE THREAD

**Issue by vtecone** [drewkeller/redmine_digest#36]
Hi for the life of me I can't get a cron to run daily let alone once.

Redmine 2.2.2.stable

Default administrator account changed  
Attachments directory writable  
Plugin assets directory writable  
RMagick available (optional)    

Environment:
  Redmine version                          2.2.2.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.11
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  openid_fix                               0.1.0
  redmine_digest                           0.2.0
  redmine_googlesss                        0.0.2
  redmine_people                           0.1.6

root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin# rake redmine:send_digest start=1 days=1 project=myproject Rails.env="productio" --trace
(in /opt/bitnami/apps/redmine/htdocs)
*\* Invoke redmine:send_digest (first_time)
*\* Execute redmine:send_digest
rake aborted!
string not matched
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in `[]='
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in`block (2 levels) in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`block in execute'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`execute'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in`invoke'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in`top_level'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in`<main>'
Tasks: TOP => redmine:send_digest
root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin#

**Comment by drewkeller** [comment]
In that command line, you have a typo. I imagine your environment is not 
really named productio, but rather production (with an n at the end)?

**Comment by vtecone** [comment]
Let me test again

On Fri, Jun 21, 2013 at 9:41 PM, drewkeller notifications@github.comwrote:

> In that command line, you have a typo. I imagine your environment is not
> really named productio, but rather production (with an n at the end)?
> 
> On 6/21/2013 9:00 PM, vtecone wrote:
> 
> > Hi for the life of me I can't get a cron to run daily let alone once.
> > 
> > Redmine 2.2.2.stable
> > 
> > Default administrator account changed
> > 
> > Attachments directory writable
> > 
> > Plugin assets directory writable
> > 
> > RMagick available (optional)
> > 
> > Environment:
> > Redmine version 2.2.2.stable
> > Ruby version 1.9.3 (x86_64-linux)
> > Rails version 3.2.11
> > Environment production
> > Database adapter Mysql2
> > Redmine plugins:
> > openid_fix 0.1.0
> > redmine_digest 0.2.0
> > redmine_googlesss 0.0.2
> > redmine_people 0.1.6
> > 
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin# rake
> > redmine:send_digest start=1 days=1 project=myproject
> > Rails.env="productio" --trace
> > (in /opt/bitnami/apps/redmine/htdocs)
> > *\* Invoke redmine:send_digest (first_time)
> > *\* Execute redmine:send_digest
> > rake aborted!
> > string not matched
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in
> > 
> > |[]='
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in|block
> > 
> > (2 levels) in '
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in
> > 
> > |call'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in|block
> > 
> > in execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in|execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in
> > 
> > |block in invoke_with_call_chain'
> > /opt/bitnami/ruby/lib/ruby/1.9.1/monitor.rb:211:in|mon_synchronize'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in
> > 
> > |invoke_with_call_chain'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in|invoke'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in
> > 
> > |invoke_task'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > (2 levels) in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in
> > 
> > |standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in|top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in
> > 
> > |block in run'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in|standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in
> > 
> > |run'
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in|'
> > /opt/bitnami/ruby/bin/rake:23:in |load'
> > /opt/bitnami/ruby/bin/rake:23:in|'
> > Tasks: TOP => redmine:send_digest
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin#
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/drewkeller/redmine_digest/issues/36.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/drewkeller/redmine_digest/issues/36#issuecomment-19851070
> .

## 

_Jason Shopshear_ • jshopshear@deathlan.com

## _T_ (760) 904-4756

Desert Weather Info http://www.desertweatherinfo.com • Jason

## Shopshearhttp://jasonshopshear.com

**Comment by vtecone** [comment]
retested with fixing typo

root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin# rake
redmine:send_digest start=1 days=1 project=myproject Rails.env="production"
--trace
(in /opt/bitnami/apps/redmine/htdocs)
*\* Invoke redmine:send_digest (first_time)
*\* Execute redmine:send_digest
rake aborted!
string not matched
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in
`[]='
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in
`block (2 levels) in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in
`call'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in
`block in execute'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in
`each'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in
`execute'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in
`block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in
`invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in
`invoke'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in
`invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in
`block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in
`each'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in
`block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in
`standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in
`top_level'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in
`block in run'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in
`standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in
`run'
/opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in
`<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in`<main>'
Tasks: TOP => redmine:send_digest
root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin#

On Fri, Jun 21, 2013 at 9:41 PM, drewkeller notifications@github.comwrote:

> In that command line, you have a typo. I imagine your environment is not
> really named productio, but rather production (with an n at the end)?
> 
> On 6/21/2013 9:00 PM, vtecone wrote:
> 
> > Hi for the life of me I can't get a cron to run daily let alone once.
> > 
> > Redmine 2.2.2.stable
> > 
> > Default administrator account changed
> > 
> > Attachments directory writable
> > 
> > Plugin assets directory writable
> > 
> > RMagick available (optional)
> > 
> > Environment:
> > Redmine version 2.2.2.stable
> > Ruby version 1.9.3 (x86_64-linux)
> > Rails version 3.2.11
> > Environment production
> > Database adapter Mysql2
> > Redmine plugins:
> > openid_fix 0.1.0
> > redmine_digest 0.2.0
> > redmine_googlesss 0.0.2
> > redmine_people 0.1.6
> > 
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin# rake
> > redmine:send_digest start=1 days=1 project=myproject
> > Rails.env="productio" --trace
> > (in /opt/bitnami/apps/redmine/htdocs)
> > *\* Invoke redmine:send_digest (first_time)
> > *\* Execute redmine:send_digest
> > rake aborted!
> > string not matched
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in
> > 
> > |[]='
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in|block
> > 
> > (2 levels) in '
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in
> > 
> > |call'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in|block
> > 
> > in execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in|execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in
> > 
> > |block in invoke_with_call_chain'
> > /opt/bitnami/ruby/lib/ruby/1.9.1/monitor.rb:211:in|mon_synchronize'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in
> > 
> > |invoke_with_call_chain'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in|invoke'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in
> > 
> > |invoke_task'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > (2 levels) in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in
> > 
> > |standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in|top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in
> > 
> > |block in run'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in|standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in
> > 
> > |run'
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in|'
> > /opt/bitnami/ruby/bin/rake:23:in |load'
> > /opt/bitnami/ruby/bin/rake:23:in|'
> > Tasks: TOP => redmine:send_digest
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin#
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/drewkeller/redmine_digest/issues/36.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/drewkeller/redmine_digest/issues/36#issuecomment-19851070
> .

## 

_Jason Shopshear_ • jshopshear@deathlan.com

## _T_ (760) 904-4756

Desert Weather Info http://www.desertweatherinfo.com • Jason

## Shopshearhttp://jasonshopshear.com

**Comment by vtecone** [comment]
It works fine when I run it from the plugin interface under control panel

On Fri, Jun 21, 2013 at 9:41 PM, drewkeller notifications@github.comwrote:

> In that command line, you have a typo. I imagine your environment is not
> really named productio, but rather production (with an n at the end)?
> 
> On 6/21/2013 9:00 PM, vtecone wrote:
> 
> > Hi for the life of me I can't get a cron to run daily let alone once.
> > 
> > Redmine 2.2.2.stable
> > 
> > Default administrator account changed
> > 
> > Attachments directory writable
> > 
> > Plugin assets directory writable
> > 
> > RMagick available (optional)
> > 
> > Environment:
> > Redmine version 2.2.2.stable
> > Ruby version 1.9.3 (x86_64-linux)
> > Rails version 3.2.11
> > Environment production
> > Database adapter Mysql2
> > Redmine plugins:
> > openid_fix 0.1.0
> > redmine_digest 0.2.0
> > redmine_googlesss 0.0.2
> > redmine_people 0.1.6
> > 
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin# rake
> > redmine:send_digest start=1 days=1 project=myproject
> > Rails.env="productio" --trace
> > (in /opt/bitnami/apps/redmine/htdocs)
> > *\* Invoke redmine:send_digest (first_time)
> > *\* Execute redmine:send_digest
> > rake aborted!
> > string not matched
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in
> > 
> > |[]='
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in|block
> > 
> > (2 levels) in '
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in
> > 
> > |call'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in|block
> > 
> > in execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in|execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in
> > 
> > |block in invoke_with_call_chain'
> > /opt/bitnami/ruby/lib/ruby/1.9.1/monitor.rb:211:in|mon_synchronize'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in
> > 
> > |invoke_with_call_chain'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in|invoke'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in
> > 
> > |invoke_task'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > (2 levels) in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in
> > 
> > |standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in|top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in
> > 
> > |block in run'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in|standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in
> > 
> > |run'
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in|'
> > /opt/bitnami/ruby/bin/rake:23:in |load'
> > /opt/bitnami/ruby/bin/rake:23:in|'
> > Tasks: TOP => redmine:send_digest
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin#
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/drewkeller/redmine_digest/issues/36.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/drewkeller/redmine_digest/issues/36#issuecomment-19851070
> .

## 

_Jason Shopshear_ • jshopshear@deathlan.com

## _T_ (760) 904-4756

Desert Weather Info http://www.desertweatherinfo.com • Jason

## Shopshearhttp://jasonshopshear.com

**Comment by vtecone** [comment]
Drew thank you for your help... I've tried everything ..

On Fri, Jun 21, 2013 at 9:41 PM, drewkeller notifications@github.comwrote:

> In that command line, you have a typo. I imagine your environment is not
> really named productio, but rather production (with an n at the end)?
> 
> On 6/21/2013 9:00 PM, vtecone wrote:
> 
> > Hi for the life of me I can't get a cron to run daily let alone once.
> > 
> > Redmine 2.2.2.stable
> > 
> > Default administrator account changed
> > 
> > Attachments directory writable
> > 
> > Plugin assets directory writable
> > 
> > RMagick available (optional)
> > 
> > Environment:
> > Redmine version 2.2.2.stable
> > Ruby version 1.9.3 (x86_64-linux)
> > Rails version 3.2.11
> > Environment production
> > Database adapter Mysql2
> > Redmine plugins:
> > openid_fix 0.1.0
> > redmine_digest 0.2.0
> > redmine_googlesss 0.0.2
> > redmine_people 0.1.6
> > 
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin# rake
> > redmine:send_digest start=1 days=1 project=myproject
> > Rails.env="productio" --trace
> > (in /opt/bitnami/apps/redmine/htdocs)
> > *\* Invoke redmine:send_digest (first_time)
> > *\* Execute redmine:send_digest
> > rake aborted!
> > string not matched
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in
> > 
> > |[]='
> > 
> > /opt/bitnami/apps/redmine/htdocs/plugins/redmine_digest/lib/tasks/digest.rake:47:in|block
> > 
> > (2 levels) in '
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in
> > 
> > |call'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in|block
> > 
> > in execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in|execute'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in
> > 
> > |block in invoke_with_call_chain'
> > /opt/bitnami/ruby/lib/ruby/1.9.1/monitor.rb:211:in|mon_synchronize'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in
> > 
> > |invoke_with_call_chain'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in|invoke'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in
> > 
> > |invoke_task'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > (2 levels) in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in
> > 
> > |each'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in|block
> > 
> > in top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in
> > 
> > |standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in|top_level'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in
> > 
> > |block in run'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in|standard_exception_handling'
> > 
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in
> > 
> > |run'
> > /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in|'
> > /opt/bitnami/ruby/bin/rake:23:in |load'
> > /opt/bitnami/ruby/bin/rake:23:in|'
> > Tasks: TOP => redmine:send_digest
> > root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin#
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/drewkeller/redmine_digest/issues/36.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/drewkeller/redmine_digest/issues/36#issuecomment-19851070
> .

## 

_Jason Shopshear_ • jshopshear@deathlan.com

## _T_ (760) 904-4756

Desert Weather Info http://www.desertweatherinfo.com • Jason

## Shopshearhttp://jasonshopshear.com

**Comment by vtecone** [comment]
root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin# rake redmine:send_digest start=1 days=1 project=myproject Rails.env="production"
(in /opt/bitnami/apps/redmine/htdocs)
rake aborted!
string not matched

Tasks: TOP => redmine:send_digest
(See full trace by running task with --trace)
root@ip-10-202-39-172:/home/bitnami/apps/redmine/htdocs/bin#

**Comment by vtecone** [comment]
Can anyone point me in the right direction just trying to get a daily digest to run...

**Comment by drewkeller** [comment]
Some other people have reported issues with line 47 in the rake.digest file. You could try the same workaround: https://github.com/drewkeller/redmine_digest/issues/29

http://stackoverflow.com/questions/17246780/redmine-digest-version-2-2-2-stable/17253588#17253588

**Comment by vtecone** [comment]
Thank you so much I will look into it.. If I can't get it going I will pay
you for your time.

On Tue, Jun 25, 2013 at 8:09 PM, drewkeller notifications@github.comwrote:

> Some other people have reported issues with line 47 in the rake.digest
> file. You could try the same workaround: #29https://github.com/drewkeller/redmine_digest/issues/29
> 
> http://stackoverflow.com/questions/17246780/redmine-digest-version-2-2-2-stable/17253588#17253588
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/drewkeller/redmine_digest/issues/36#issuecomment-20024788
> .

## 

_Jason Shopshear_ • jshopshear@deathlan.com

## _T_ (760) 904-4756

Desert Weather Info http://www.desertweatherinfo.com • Jason

## Shopshearhttp://jasonshopshear.com

**Comment by vtecone** [comment]
That was it......... !!!!!!! Thank you .. If you had a donate button I
would be all over it... I the plugin works great now..

On Tue, Jun 25, 2013 at 8:28 PM, Jason Shopshear jshopshear@deathlan.comwrote:

> Thank you so much I will look into it.. If I can't get it going I will pay
> you for your time.
> 
> On Tue, Jun 25, 2013 at 8:09 PM, drewkeller notifications@github.comwrote:
> 
> > Some other people have reported issues with line 47 in the rake.digest
> > file. You could try the same workaround: #29https://github.com/drewkeller/redmine_digest/issues/29
> > 
> > http://stackoverflow.com/questions/17246780/redmine-digest-version-2-2-2-stable/17253588#17253588
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/drewkeller/redmine_digest/issues/36#issuecomment-20024788
> > .
> 
> ## 
> 
> _Jason Shopshear_ • jshopshear@deathlan.com
> 
> ## _T_ (760) 904-4756
> 
> ## Desert Weather Info http://www.desertweatherinfo.com • Jason Shopshearhttp://jasonshopshear.com

## 

_Jason Shopshear_ • jshopshear@deathlan.com

## _T_ (760) 904-4756

Desert Weather Info http://www.desertweatherinfo.com • Jason

## Shopshearhttp://jasonshopshear.com

**Comment by drewkeller** [comment]
Cool, glad you got it working. 

I'm not sure how to add a donate button on github, but I do have one on my website: http://www.drewkeller.com.

I think we can close this issue now?

**Comment by drewkeller** [comment]
If that was you that posted the stackoverflow question, maybe you could give me an upvote?

**Comment by drewkeller** [comment]
ok, thanks!
