### ISSUE TITLE
No events were found for project

### ISSUE THREAD

**Issue by GlenRayward** [drewkeller/redmine_digest#4]
Good work on getting this digest 

When doing it from the command line using: 
c:\Program Files\BitNami Redmine Stack\apps\redmine>rake redmine:send_digest start=7 days=7 RAILS_ENV="production"
(in c:/Program Files/BitNami Redmine Stack/apps/redmine)
I get:
Summarizing: 2011-08-17 to 2011-08-24 (7 days)
From 17 August 2011 to 23 August 2011
No events were found for project SandBoxProject.
Digest done.

Where I'm getting lots of events sent though email normally...

Cheers

**Comment by drewkeller** [comment]
I've only tested the digest on redmine 1.2.0 and 1.2.1. Do you happen to be using some other version?
The part of the code that fills the events I mainly copied _ahem_ "reused" from a project's activity page.

**Comment by GlenRayward** [comment]
I'm using 1.2.1-0 :)

-----Original Message-----

**Comment by drewkeller** [comment]
Perhaps all of your events were from today? If so, starting 7 days ago from yesterday and including 7 days.... does not include today. Try start=7 and include=8. Also make sure your project has some users actually assigned to it. I just tried a simple set up with a fresh Bitnami redmine and it worked for me.

<pre>
@echo off
::set environment=development
set environment=production
set folder=c:\Program Files\BitNami Redmine Stack
set redmine=redmine
set rakefile=%folder%/apps/%redmine%/Rakefile

CALL C:\PROGRA~1\BITNAM~1\scripts\setenv.bat

cd "%folder%\ruby\bin"
::ruby rake -f "%rakefile%" db:migrate_plugins RAILS_ENV=%environment% --trace

rake redmine:send_digest start=7 days=8 RAILS_ENV="production" -f "%rakefile%"

pause
</pre>


<pre>

(in c:/Program Files/BitNami Redmine Stack/ruby/bin)

=====
Start: 7
Days : 8
** Processing project 'sandbox'...
Summarizing: 2011-08-17 to 2011-08-25 (8 days)
From 08/17/2011 to 08/24/2011
Found 1 events.
Email sent.
Sent digest: [sandbox] Activity: 1 events (from 08/17/2011 to 08/24/2011)
Digest done.
</pre>

**Comment by GlenRayward** [comment]
I have events in the last 7 days, a few users (assigned to projects), a few projects
I've tried 30 days too which includes my install date and nothing...
Do you have regular emails getting sent to users as well as digest? or do I have to set it to something special?

-----Original Message-----

**Comment by drewkeller** [comment]
I guess I'll have to add some more debugging output to the part where it fills events to see why they are not being included. I have some test users set up and they received event notifications according to their settings when I tested it.

**Comment by drewkeller** [comment]
We had a power outage yesterday so the server wasn't running when it normally sends the digest, so I had an opportunity to run this manually on our production server that has about 300 tickets and 20 real users and 1 event from yesterday (news item). Worked fine for me (I used the "Send digests for all digest-enabled projects" after testing with "Send a test email to your email address"). I also ran a test for the last couple days to include a new ticket event and that worked, too. This was using the updated version that I just committed to github, but that didn't change anything in the activity section.

If you want to generate a log from the development environment and email it to me, I might be able to figure something out from it. My address is drew & drewkeller.com (substitute with an @ of course). Please clear the log first or it will be quite large (delete it or make sure it's not present at C:\Program Files\BitNami Redmine Stack\apps\redmine\log\development.log).

**Comment by GlenRayward** [comment]
Hi Drew,

> With mongrel running in the console, try to send the digest. If you get an error, it should print out some stuff in the console.
> I did send test and send digest from the settings tab yesterday thinking this is what you wanted and It did not produce any errors in the console.

You mentioned doing these tests could break my database, do you know if I can just copy the whole bitnami folder (with server shutdown) and restore it by copying it back if things go haywire?

I've done it before when installing plugins and it worked then (well it seemed to)

Cheers
-Glen

-----Original Message-----

**Comment by drewkeller** [comment]
Breaking the database is not likely. I wouldn't worry too much about it myself. But yes, you should be able to backup the mysql data folder and paste it back in if you really need to (you don't need to copy the whole bitnami folder). I don't know why bitnami didn't include phpmyadmin. It's way more user friendly.

If you're seeing some kind of error on the web page, it really ought to be showing up in more detail in the console. I don't know why it wouldn't be.

**Comment by cforce** [comment]
We are using redmine 1.2.1 and have eaxtly the same bug.
There are many different events in our activity tab for projects the digest module is activ and the period (7x7).
Our script look like this 

rake -f /redmine/Rakefile redmine:send_digest start=7 days=7 RAILS_ENV="production" --trace >> /var/log/apache2/redmine_digest.log

and this is the ouput

(in /usr/local/lib/redmine-1.2.1)
*\* Invoke redmine:send_digest (first_time)
*\* Execute redmine:send_digest

# 

Start: 7
Days : 7
*\* Processing project 'SUS'...
Summarizing: 2011-08-19 to 2011-08-26 (7 days)
From 08/19/2011 to 08/25/2011
No events were found for project SUS.
*\* Processing project 'Spielwiese'...
Summarizing: 2011-08-19 to 2011-08-26 (7 days)
From 08/19/2011 to 08/25/2011
No events were found for project Spielwiese.
*\* Processing project 'Infra'...
Summarizing: 2011-08-19 to 2011-08-26 (7 days)
From 08/19/2011 to 08/25/2011
No events were found for project Infra.
Digest done.

We mass changed 10 tickets and although author and other person in this project are subscribed of digest no events are found and no emails are send.

**Comment by cforce** [comment]
The sh script with cmd

rake -f /redmine/Rakefile redmine:send_digest start=7 days=7 RAILS_ENV="production" --trace >> /var/log/apache2/redmine_digest.log

never terminates on our mchaine and the cpu is abou 100%  (2 processor and 5 GB RAM)).. Looks like an infinite loop

**Comment by drewkeller** [comment]
Please see if this is fixed in the latest commit.

**Comment by cforce** [comment]
No. doesn't change things.

The digest module is activ for 3 projects "Spielweise", SUS, and "Infratstrukturdienste"
In all of this projects i changed as user test (mymail@mail.de) issue status from seomewhere to closed
I my activity pane i can see this changes for today
"Receive an email periodically that shows project activity." is on for user test
In plugins admin config i set "Days ago to start=7 and "Day to include" to 7 and clicked apply. (THe values are set back to default value "1" , it doesn not backup the changes or doesn't show them at all)
Then i click "Send a test email to your email address" i get following resut:
A digest was processed for mymail@mail.de.
2 projects were processed.
No events were found for project SUS.
No events were found for project Infratstrukturdienste.

Why is "Spielweise" missing?
Why are no events found?
Why i don't get any email?

**Comment by cforce** [comment]
Btw i found on my apache log:

Sending test email to mymail@mail.de.

# 

Start: 1
Days : 1
*\* Processing project 'SUS'...
Summarizing: 2011-08-28 to 2011-08-29 (1 days)
von 28.08.2011 bis 28.08.2011
No events were found for project SUS.
*\* Processing project 'Infratstrukturdienste'...
Summarizing: 2011-08-28 to 2011-08-29 (1 days)
von 28.08.2011 bis 28.08.2011
No events were found for project Infratstrukturdienste.
A digest was processed for mymail@mail.de.<p>2 projects were processed.<br />No events were found for project SUS.<br />No events were found for project Infratstrukturdienste.</p>

The values are not saved at all, but even changes from today shall create events!

**Comment by drewkeller** [comment]
I think part of this is due to the plugin having it's name changed between v0.0.1 and v0.1.0 and not having the database synchronized with the name change. Be sure to perform the db:migrate_plugins and then recheck all of the settings.

**Comment by drewkeller** [comment]
If you continue to have problems, download the extra_debug branch and run the server in the console so the debug messages are visible.

**Comment by cforce** [comment]
I cleaned Migration Table DELETE FROM `schema_migrations` WHERE `version` LIKE '%digest%'

and migrated again..

Migrating redmine_digest...
==  CreateDigestAccounts: migrating ===========================================
-- create_table(:digest_accounts, {:force=>true})
   -> 0.0190s
==  CreateDigestAccounts: migrated (0.0193s) ==================================

I restarted redmine and set digest config to 14 days all (now it shows the saved values in dialogc also

When i click "Send a test email to your email address" i get an Internal error now for row

logger.error e.message, e.backtrace unless logger.nil?

Wrong argument count?

F, [2011-08-31T13:24:46.485534 #11876] FATAL -- : 
ArgumentError (wrong number of arguments (2 for 1)):
  vendor/plugins/redmine_digest/app/controllers/digest_controller.rb:74:in `error'
  vendor/plugins/redmine_digest/app/controllers/digest_controller.rb:74:in`digest_send'
  vendor/plugins/redmine_digest/app/controllers/digest_controller.rb:93:in `test_email'
  passenger (2.2.14) lib/phusion_passenger/rack/request_handler.rb:92:in`process_request'
  passenger (2.2.14) lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:441:in`start_request_handler'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:381:in `handle_spawn_application'
  passenger (2.2.14) lib/phusion_passenger/utils.rb:252:in`safe_fork'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:377:in `handle_spawn_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in`**send**'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:163:in `start'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:222:in`start'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server_collection.rb:126:in`lookup_or_add'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server_collection.rb:80:in`synchronize'
  passenger (2.2.14) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:255:in`spawn_rails_application'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:287:in`handle_spawn_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in`main_loop'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'

**Comment by GlenRayward** [comment]
I'm using that latest downloaded an hour ago,
It ran from cmd line once with no Users Digests 'Active'
And it looked like it worked processing the data,
I sent a test emails and it had the SSL error but still sent SOME updates,(one projects) 
I did a 'send digests' from the settings box and it said that it worked (but no users are configured to receive)
So i changed a users setting to Digests = Active
And i got the following with Local Avatar plugin installed:

Start: 7
Days : 8
*\* Processing project 'Project 1'...
Summarizing: 2011-08-25 to 2011-09-02 (8 days)
From 25 August 2011 to 01 September 2011
Found 7 events.
Email sent.
Sent digest: [Project 1] Activity: 7 events (from 25 august 2011 to 01 september 2011)
*\* Processing project 'Project 1'...
Summarizing: 2011-08-25 to 2011-09-02 (8 days)
From 25 August 2011 to 01 September 2011
Found 1 events.
rake aborted!
undefined method `ssl?' for nil:NilClass
On line #47 of vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml

```
44: <div id="activity">
45: <ul>
46: <% @events_by_day.keys.sort.each do |day| %>
47: <li>
48: <h3><%= format_date(day) %></h3>
49: <dl>
50: <% @events_by_day[day].sort {|x,y| x.event_datetime <=> y.event_datetime }.each do |e| -%>

app/helpers/application_helper.rb:879:in `avatar_without_local'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:47:in `_run_rhtml_vendor47plugins47redmine_digest47app47vie
```

ws47digest_mailer47digest46text46html46rhtml'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:44:in `each'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:44:in`_run_rhtml_vendor47plugins47redmine_digest47app47vie
ws47digest_mailer47digest46text46html46rhtml'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in `each'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in`_run_rhtml_vendor47plugins47redmine_digest47app47vie
ws47digest_mailer47digest46text46html46rhtml'
    app/models/mailer.rb:417:in `render_multipart'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:31:in`digest'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:159:in `digests'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:134:in`each'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:134:in `digests'
    rake (0.8.7) lib/rake.rb:636:in`call'
    rake (0.8.7) lib/rake.rb:636:in `execute'
    rake (0.8.7) lib/rake.rb:631:in`each'
    rake (0.8.7) lib/rake.rb:631:in `execute'
    rake (0.8.7) lib/rake.rb:597:in`invoke_with_call_chain'
    c:/Program Files/BitNami Redmine Stack/ruby/lib/ruby/1.8/monitor.rb:242:in `synchronize'
    rake (0.8.7) lib/rake.rb:590:in`invoke_with_call_chain'
    rake (0.8.7) lib/rake.rb:583:in `invoke'
    rake (0.8.7) lib/rake.rb:2051:in`invoke_task'
    rake (0.8.7) lib/rake.rb:2029:in `top_level'
    rake (0.8.7) lib/rake.rb:2029:in`each'
    rake (0.8.7) lib/rake.rb:2029:in `top_level'
    rake (0.8.7) lib/rake.rb:2068:in`standard_exception_handling'
    rake (0.8.7) lib/rake.rb:2023:in `top_level'
    rake (0.8.7) lib/rake.rb:2001:in`run'
    rake (0.8.7) lib/rake.rb:2068:in `standard_exception_handling'
    rake (0.8.7) lib/rake.rb:1998:in`run'
    rake (0.8.7) bin/rake:31
    c:/Program Files/BitNami Redmine Stack/ruby/bin/rake:19:in `load'
    c:/Program Files/BitNami Redmine Stack/ruby/bin/rake:19

And after removing the Local Avatar plugin, it died even earlier:

# 

Start: 7
Days : 8
*\* Processing project 'Project 1'...
Summarizing: 2011-08-25 to 2011-09-02 (8 days)
From 25 August 2011 to 01 September 2011
Found 7 events.
rake aborted!
undefined method `ssl?' for nil:NilClass
On line #47 of vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml

```
44: <div id="activity">
45: <ul>
46: <% @events_by_day.keys.sort.each do |day| %>
47: <li>
48: <h3><%= format_date(day) %></h3>
49: <dl>
50: <% @events_by_day[day].sort {|x,y| x.event_datetime <=> y.event_datetime }.each do |e| -%>

app/helpers/application_helper.rb:879:in `avatar'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:47:in `_run_rhtml_vendor47plugins47redmine_digest47app47vie
```

ws47digest_mailer47digest46text46html46rhtml'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:44:in `each'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:44:in`_run_rhtml_vendor47plugins47redmine_digest47app47vie
ws47digest_mailer47digest46text46html46rhtml'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in `each'
    vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in`_run_rhtml_vendor47plugins47redmine_digest47app47vie
ws47digest_mailer47digest46text46html46rhtml'
    app/models/mailer.rb:417:in `render_multipart'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:31:in`digest'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:159:in `digests'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:134:in`each'
    vendor/plugins/redmine_digest/app/models/digest_mailer.rb:134:in `digests'
    rake (0.8.7) lib/rake.rb:636:in`call'
    rake (0.8.7) lib/rake.rb:636:in `execute'
    rake (0.8.7) lib/rake.rb:631:in`each'
    rake (0.8.7) lib/rake.rb:631:in `execute'
    rake (0.8.7) lib/rake.rb:597:in`invoke_with_call_chain'
    c:/Program Files/BitNami Redmine Stack/ruby/lib/ruby/1.8/monitor.rb:242:in `synchronize'
    rake (0.8.7) lib/rake.rb:590:in`invoke_with_call_chain'
    rake (0.8.7) lib/rake.rb:583:in `invoke'
    rake (0.8.7) lib/rake.rb:2051:in`invoke_task'
    rake (0.8.7) lib/rake.rb:2029:in `top_level'
    rake (0.8.7) lib/rake.rb:2029:in`each'
    rake (0.8.7) lib/rake.rb:2029:in `top_level'
    rake (0.8.7) lib/rake.rb:2068:in`standard_exception_handling'
    rake (0.8.7) lib/rake.rb:2023:in `top_level'
    rake (0.8.7) lib/rake.rb:2001:in`run'
    rake (0.8.7) lib/rake.rb:2068:in `standard_exception_handling'
    rake (0.8.7) lib/rake.rb:1998:in`run'
    rake (0.8.7) bin/rake:31
    c:/Program Files/BitNami Redmine Stack/ruby/bin/rake:19:in `load'
    c:/Program Files/BitNami Redmine Stack/ruby/bin/rake:19

Note my main contributor has a Local Avatar, the rest use Gravatar Wavatars.
The emails that partially worked included the Local Avatar.

I also still don’t see anything extra in the mongrel window.

Cheers
-Glen

-----Original Message-----

**Comment by drewkeller** [comment]
It looks like you're not running the branch with extra debug info. To download that one, select it under the "Switch branches" option. Then you can click the download button and it should show you that you are downloading from the "extra_debug" branch (if it says master branch, it's not the right one).

When you start the server, you should have (note the extra lines in the middle)...

<pre>
** Starting Mongrel listening at 127.0.0.1:3001
** Starting Rails with development environment...
** Mounting Rails at /redmine...
Registered redmine_digest plugin, version 0.1.0
Applying UserPatch
Added relation to User for digest_account
** Rails loaded.
** Loading any Rails specific GemPlugins
** Signals ready.  INT => stop (no restart).
** Mongrel 1.1.5 available at 127.0.0.1:3001
** Use CTRL-C to stop.</pre>


Do you really have two projects named 'Project 1'?

**Comment by GlenRayward** [comment]
Sorry!

And no I changed the name of the project to project 1, i thought they were the same project but maybe not.

I'm running the debug branch now downloaded 20 mins ago.
With no users configured for Digests=Active ...
The Test email says it works now, BUT in the email there is now: "No data to display"
Even though it found 7 events in one project and 32 in the other.

Mongrel doesn’t show any errors.

Now with 1 user active:
Same result.

Now 1 active, send digest for all...
Same Result.

Cheers
-Glen

-----Original Message-----

**Comment by GlenRayward** [comment]
Ohh and the Same result for raking from console.

*\* Processing project 'Project 1'...
Summarizing: 2011-08-26 to 2011-09-03 (8 days)
From 26 August 2011 to 02 September 2011
Fetching activity
Activity.scope: ["issues", "changesets", "files", "wiki_edits"]
Found 7 events.
Default setting for whether digest is active for users:
Email sent.

Once its working, will it include events that get sent from other plugins such as 'Arch Decisions'
(Which normally get event updates from regular redmine emails)

Thanks!
-Glen

-----Original Message-----

**Comment by drewkeller** [comment]
Believe it or not, that is helpful. This narrows the problem down to the sort function set in the mail processor is being forgotten by the mail formatter.

mail processor:

<pre>body[:events_by_day] = events.group_by(&:event_date)</pre>


mail formatter (all ^s are supposed to be < or >):

<pre>^% if @events_by_day.blank? -%^^p^^%= l(:label_no_data) %^^/p^</pre>


So the question is, what is happening in the group_by function. I'll add some more debugging around that later tonight.

The event selector is currently hardcoded to turn on all the options that appear in Redmine's Activity page and use that for selecting events. If another plugin adds more options on the activity page, it would not be hard to include them in the digest at some point in the future.

**Comment by drewkeller** [comment]
Well, the "No data" in the email was easy to explain: I forgot to remove some debug code I was using to test a "no data" situation. I added some more debugging for events, but I imagine it will be working for you now with the update.

**Comment by cforce** [comment]
There is still noe events processed even if i create a new ticket for user and project digest module is active

**Comment by drewkeller** [comment]
@cforce, please download the extra_debug branch and run the server in the console so the debug messages are visible. I need more details.

**Comment by cforce** [comment]
Your debug branch seems work, what is diff to master?

**Comment by drewkeller** [comment]
Thanks for the feedback. I'm going to close this issue unless you have any further problems.

**Comment by GlenRayward** [comment]
Ok, does the main branch work now?

-----Original Message-----

**Comment by drewkeller** [comment]
I applied all of the differences from the debug branch to the main 
branch, except for all the extra debug messages. As far as I know, it 
should work (I was never able to duplicate this issue myself).

**Comment by GlenRayward** [comment]
Cheers
:D

-----Original Message-----
