### ISSUE TITLE
Don´t send email to ALL project members?

### ISSUE THREAD

**Issue by jmartsch** [drewkeller/redmine_digest#5]
In my projects i always add ALL employees from my company as possible watchers. So when i send a digest EVERY project member gets the digest, even if he isn´t assigned as a watcher to any issue. 

Wouldn´t it be better if the email only contains relevant information for each user? Just include the progress of an issue if the recipient is an assignee or watcher for that issue?

What do you think about that?

**Comment by drewkeller** [comment]
I suppose it's a question of scope.

For small projects or slow moving ones, all members of a project can be made aware of what's going on in the project without it being too annoying. On large projects or really active ones, I imagine even a digest could get noisy.

There is room for more complex setups, but the same could be said for Redmine's own notifications.

I have several small projects and each one has different team members, so actually v0.0.1 satisfied what I was looking for. At some point I may add some more features, but it will be slower development. As I've said before, improvement patches are welcome. There are a number of points in http://www.redmine.org/issues/8241(and other issues linked in the comments of that one) that would be nice to have implemented.
