### ISSUE TITLE
rake aborted! undefined method `ssl?'

### ISSUE THREAD

**Issue by dcastanos** [drewkeller/redmine_digest#8]
I've just installed the latest version of your plugin and I keep having this error when I execute the digest command:

rake aborted! undefined method `ssl?'

The command I execute: /usr/bin/rake --trace redmine:send_digest start=1 days=1 project=3 RAILS_ENV=production

Here is the trace:

*\* Invoke redmine:send_digest (first_time)
*\* Execute redmine:send_digest
# 

Start: 1
Days : 1
*\* Processing project 'eQRehab'...
Summarizing: 2011-09-13 to 2011-09-14 (1 days)
From 13 September 2011 to 13 September 2011
Found 2 events.
rake aborted!
undefined method `ssl?' for nil:NilClass
On line #47 of vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml

```
44: <div id="activity">
45: <ul>
46: <% @events_by_day.keys.sort.each do |day| %>
47: <li>
48: <h3><%= format_date(day) %></h3>
49: <dl>
50: <% @events_by_day[day].sort {|x,y| x.event_datetime <=> y.event_datetime }.each do |e| -%>

app/helpers/application_helper.rb:879:in `avatar'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:47:in `_run_rhtml_vendor47plugins47redmine_digest47app47views47digest_mailer47digest46text46html46rhtml'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:44:in `each'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:44:in `_run_rhtml_vendor47plugins47redmine_digest47app47views47digest_mailer47digest46text46html46rhtml'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in `each'
vendor/plugins/redmine_digest/app/views/digest_mailer/digest.text.html.rhtml:40:in `_run_rhtml_vendor47plugins47redmine_digest47app47views47digest_mailer47digest46text46html46rhtml'
app/models/mailer.rb:417:in `render_multipart'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:31:in `digest'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:159:in `digests'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:134:in `each'
vendor/plugins/redmine_digest/app/models/digest_mailer.rb:134:in `digests'
rake (0.8.7) lib/rake.rb:636:in `call'
rake (0.8.7) lib/rake.rb:636:in `execute'
rake (0.8.7) lib/rake.rb:631:in `each'
rake (0.8.7) lib/rake.rb:631:in `execute'
rake (0.8.7) lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
rake (0.8.7) lib/rake.rb:590:in `invoke_with_call_chain'
rake (0.8.7) lib/rake.rb:583:in `invoke'
rake (0.8.7) lib/rake.rb:2051:in `invoke_task'
rake (0.8.7) lib/rake.rb:2029:in `top_level'
rake (0.8.7) lib/rake.rb:2029:in `each'
rake (0.8.7) lib/rake.rb:2029:in `top_level'
rake (0.8.7) lib/rake.rb:2068:in `standard_exception_handling'
rake (0.8.7) lib/rake.rb:2023:in `top_level'
rake (0.8.7) lib/rake.rb:2001:in `run'
rake (0.8.7) lib/rake.rb:2068:in `standard_exception_handling'
rake (0.8.7) lib/rake.rb:1998:in `run'
rake (0.8.7) bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
```

Environment:
- Redmine 1.2.1
- Apache2 + Passenger
- Postgresql 8.3

Gem List:
actionmailer (2.3.11)
actionpack (2.3.11)
activerecord (2.3.11)
activeresource (2.3.11)
activesupport (2.3.11)
Ascii85 (1.0.1)
daemon_controller (0.2.6)
fastthread (1.0.7)
holidays (1.0.3)
i18n (0.4.2)
icalendar (1.1.6)
mysql (2.8.1)
nokogiri (1.5.0)
open-uri-cached (0.0.4)
passenger (3.0.9)
pdf-reader (0.10.0)
postgres-pr (0.6.3)
prawn (0.12.0)
rack (1.1.2, 1.1.0)
rails (2.3.11)
rake (0.8.7)
ttfunk (1.0.2)

**Comment by dcastanos** [comment]
Sorry, didn't realize the issue was already reported.
I just downloaded the plugin yesterday, so I can imagen your latest patch is not included on the trunk version.
I try the last commited version and keep you posted.

**Comment by dcastanos** [comment]
With last commit problem is solved.

Thanks!

**Comment by drewkeller** [comment]
I am not able to duplicate this.
Can you switch to the extra_debug branch, download it, run it, and then 
post the results?
